---
name: Norminette

on:
  pull_request:
    branches:
      - main

jobs:
  check-norminette:
    name: Norminette
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Norminette
        uses: 42School/norminette@3.3.59
        with:
          args: '-RCheckForbiddenSourceHeader'