name: Norminette and parsing tests

on:
  pull_request:
    branches:
      - main

jobs:
  check-norminette:
    name: Norminette & parsing test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Norminette
        uses: 42School/norminette@3.3.59
        with:
          args: '-RCheckForbiddenSourceHeader'

      - name: Configuring Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install test dependencies
        run: pip install pytest

      - name: Running unit tests
        run: make test
